baseURL = "https://themicrobrainlab.netlify.app"
languageCode = "en-us"
title = "The µ-brain Lab"
theme = "hugo-xmin"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "borland"
    tabWidth = 4


[taxonomies]
   tag = "tags"
   category = "categories"

   
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4


[params]
    footer = """&copy; [The Micro Brain Lab](https://github.com/the-micro-brain-lab) 2020 - 2025"""

